### PR TITLE
Fixing logic around evaluating SourceFilePath in LogSource constructor

### LINKED ISSUE #5: new LogSource() fails if mismatch between o/s calling code compiled on, and code executing on
Affects constructor `public LogSource([CallerFilePath] string sourceFilePath = null)`, which is the advocated constructor to use.

Internally, there is logic to determine the directorySeperatorChar. For .NET Standard 1.1, 1.3, 2.0, and .NET 4.5, this selects the character based upon the runtime.

The issue arises because CallerFilePath does not return a path based upon a runtime value, but rather a compile time value (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerfilepathattribute?view=netstandard-2.0).

When the calling code was compiled on a different o/s to the o/s the code is currently executing on, this means the subsequent constructor code is not able to split the path, causing this line to fail:
```
private static string GetFilename(IEnumerable<string> filePath)
{
   return filePath.Last();
}
```

Discovered when using Dapplo.Confluence from a Linux server, under .NET Core

### PR DESCRIPTION
**Pull request by mpritch599**
Replacing path logic dependent on Runtime o/s with something based upon the content of the supplied string (default value of [CallerFilePath] is compile-time generated)

Resolves #5

### CODE REVIEW

**Comment by mpritch599** [comment]
@Lakritzator would you mind taking a look please? Currently this is causing us some issues when using Dapplo.Confluence on a Linux host.

**Review by Lakritzator — APPROVED** [review]
That is a very nice solution, clean and simple.

**Comment by Lakritzator** [comment]
Btw. I've also updated the Dapplo.Confluence library, so it takes the newest Dapplo.Log
This doesn't force you to specify an additional direct dependency, to get the newer version.

**Comment by mpritch599** [comment]
Excellent - thanks! All working for me now on Linux under .NET core
Plus extra thanks for the update on the Dapplo.Confluence package!

**Pull request merged**
